# Generated by Django 4.0.3 on 2022-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switches',
            name='switch_6',
            field=models.BooleanField(default=False),
        ),
    ]
